---
chains:
  - name: "localhost"
    id: "371337"
    rpc:
      http: "http://localhost:8545"
      ws: "ws://localhost:8545"
db:
  dsn: "postgresql://localhost:5432/mode_ephemeral?sslmode=disable&replication=database"
  wipe: false
sync:
  enabled: true
  startBlock: 0
  blockBatchCount: 10000
ql:
  port: 50091
metrics:
  port: 6060
